### ISSUE TITLE
parse_and_stack output (dcmstack object)

### ISSUE THREAD

**Issue by TheChymera** [moloney/dcmstack#31]
@moloney  [a while ago](https://github.com/moloney/dcmstack/issues/28) you recommended the `parse_and_stack` function for automatically stacking dicons with the same echo time together. I am trying to use this function, but I have no idea what to do with its output.

This:

```
from os import listdir
from dcmstack import parse_and_stack
import numpy as np

mydir = "/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/"

print(mydir)
filelist = listdir(mydir)
myfiles = [mydir+myfile for myfile in filelist]
results = parse_and_stack(myfiles)
print(results)
print(np.shape(results))
print(type(results))
```

prints:

```
/home/chymera/data/dc.rs/export_ME/dicom/4457/1/EPI/
{(u'2.16.756.5.5.100.9223372038926637660.20904.1423396754.1', 50001, u'T2S_EP_Feb2015_multi', (-0.9999965999, -0.002201215161, -0.001398168101, -0.002201267133, 0.9999975766, 3.563401135e-05)): <dcmstack.dcmstack.DicomStack object at 0x7fb3df4cd450>}
()
<type 'dict'>
[Finished in 561.182s]
```

what can I do with that dict? It seems to me, the function creates no files. What other function do I need to pass the dict to, to get the files I want?

**Comment by moloney** [comment]
Have you looked at the docs? 

Everything you need to do to produce a Nifti file is covered in the "Introduction" section.

https://dcmstack.readthedocs.org/en/latest/
