### ISSUE TITLE
Please put dcmstack on pypi

### ISSUE THREAD

**Issue by chrisfilo** [moloney/dcmstack#41]
```
$ pip install dcmstack
Collecting dcmstack
  Could not find a version that satisfies the requirement dcmstack (from versions: )
No matching distribution found for dcmstack
```

https://pypi.python.org/pypi?%3Aaction=search&term=dcmstack&submit=search

**Comment by FredLoney** [comment]
Good idea. Note, however, that the current master version is 0.7.0.dev0, which would not be found by default with pip per the pip [Reference Guide](http://pip.readthedocs.org/en/stable/reference/pip_install/#pre-release-versions). It is a good practice to only publish a major.minor.micro tag release to PyPI. Therefore, the PyPI release should be built from the prior version tag snapshot or from a new 0.7.0 version tag. The work-around is to use the pip [VCS format](http://pip.readthedocs.org/en/stable/reference/pip_install/#vcs-support):

    pip install -e git+git://github.com/moloney/dcmstack.git#egg=dcmstack

**Comment by satra** [comment]
@FredLoney - just checking on this. is a new release coming anytime soon?

**Comment by ghisvail** [comment]
Same here, can we expect an upload on PyPI at some point please?

**Comment by moloney** [comment]
Going to tackle this one for the next release with python 2/3 support.

**Comment by moloney** [comment]
Version 0.7 is on pypi now.

**Comment by FredLoney** [comment]
Thanks, Brendan, that's a handy utility.

Fred
