### ISSUE TITLE
Doesn't appear to read Siemens .IMA files

### ISSUE THREAD

**Issue by seldamat** [moloney/dcmstack#50]
Provided Siemens .IMA files as input - program returned '0 dicom files found.'

**Comment by neurolabusc** [comment]
In my case I just appended the .dcm extension from the command line using
`find . -type f -exec mv '{}' '{}'.dcm \;`

**Comment by ashgillman** [comment]
`dcmstack --file-ext .IMA` works for me

**Comment by moloney** [comment]
Yes the `--file-ext` option is supposed to be the solution here.
