### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by hamiltonjp** [moloney/dcmstack#63]
Greetings--

Just trying out dcmstack --embed-meta option with a 4D dataset (3 space, one time) comprising many 2D DICOM slices acquired on a new Siemens Prisma 3T scanner. See attached compressed sample DICOM slice...

When I run:
dcmstack --embed-meta ./DICOM_dir
I get the error:
ValueError: could not convert string to float: Amadeus

In this case, the string Amadeus has been used by our MRI sysadmin to anonymize various patient-identifying fields such as:
StudyDescription: 'Amadeus'
PatientID: 'Amadeus'
PatientBirthDate: 'Amadeus'
PatientSex: 'Amadeus'
PatientAge: 'Amadeus'

Any help?

Tusen tack from Sweden...

Paul

[1.2.752.24.5.2900739981.2018112833518.27259337-13-5-8y6tlt.dcm.zip](https://github.com/moloney/dcmstack/files/3388916/1.2.752.24.5.2900739981.2018112833518.27259337-13-5-8y6tlt.dcm.zip)

**Comment by moloney** [comment]
When anonymizing DICOM files, the placeholder values should still be valid for the VR of the element.  For example when anonymizing dates I will typically use 19000101 or something similar.
