### ISSUE TITLE
pytest errors

### ISSUE THREAD

**Issue by alcir** [moloney/dcmstack#65]
Hello.
Sorry I'm a totally dumb.

(Python 3.7)
If I run `python setup.py test` I get some warnings, but at the end _Ran 136 tests in 3.420s OK_
Same thing with `nosetests`.

But if I use `pytest`, I get `101 failed, 35 passed, 187 warnings in 4.06 seconds`. Eventually you can see the output here: https://paste.centos.org/view/b4445e5a

**Comment by moloney** [comment]
The tests were written with Nose, so this is expected.  I use pytest in my newer projects, by dcmstack predates it (or at least its rise in popularity).
