### ISSUE TITLE
cut new release?

### ISSUE THREAD

**Issue by mgxd** [moloney/dcmstack#66]
To get in fa24702f09cff111a76297e9f01240d06b4cd1a2 and play nice with nibabel once again

**Comment by yarikoptic** [comment]
please please please!

**Comment by yarikoptic** [comment]
should be a straightforward release -- not much changes since the last one.  Please let me know @moloney if you would like a direct assistance to make it happen (I am also yarikoptic on pypi ;))

**Comment by moloney** [comment]
I fixed some failing tests and pushed the new release

**Comment by mgxd** [comment]
thanks @moloney
