### ISSUE TITLE
What is the current state with respect to enhanced MRI (3D DICOMs)?

### ISSUE THREAD

**Issue by Spenhouet** [moloney/dcmstack#71]
I just tested an enhanced MR image from a Siemens device and got an exception telling me that `time` is missing:

> The extension is not valid: Missing required base classification time

dcm2niix had no issue converting the enhanced MR image.

Should this generally work? Or is this not yet implemented?

I did successfully load the enhanced MR image via pydicom, but it fails on adding it to the stack:

```Python
my_stack = dcmstack.DicomStack()
src_dcm = pydicom.read_file(str(dicom_file_path))
my_stack.add_dcm(src_dcm)  #<- fails here
```

What is still missing for this to work? Could you need support implementing this? Do you need an example file that I can send you?

**Comment by Spenhouet** [comment]
@moloney Any feedback ob this?

**Comment by moloney** [comment]
Sorry to be so slow to reply.  My colleague and some other folks have done some work to improve "enhanced" (multiframe) handling in nibabel, but it isn't leveraged in dcmstack. At this point I prefer to put any time I have towards getting dcmstack functionality into nibabel, rather than implementing new functionality here.

**Comment by Spenhouet** [comment]
@moloney Thank you for your reply and the clarification on the maintenance / state of this project.
I was not aware of the efforts put into nibabel and that the goal is to provide the current dcmstack functionality in nibabel. That is great news. How can we follow the state of these efforts? Are there open issues on the nibabel project with respect to this which you can link to? Or is there another way to follow the progress?

We will probably need to switch to the new nibabel implementation as soon as it is available. As of the coming October all Siemens devices here will be switched/updated to "enhanced" (multiframe).

**Comment by Spenhouet** [comment]
I found this repository: https://github.com/matthew-brett/czi-nibabel (not sure if that is supposed to be public).
This looks like a really cool project!

Going by this:

- Project overview: https://github.com/matthew-brett/czi-nibabel/blob/master/dicom_to_xarray.md
- Milestones and Deliverables: https://github.com/matthew-brett/czi-nibabel/blob/master/milestones.md

The grant starts at January 1, 2021 and the milestone is to have the DICOM to NIfTI integration into Nibabel ready 3 months after that. So basically this functionality is supposed to be available in April 2021. Correct me if that is a wrong assumption.

Not sure if that includes the multiframe handling.

Sadly we will have to somehow cope with this differently. As mentioned, as of October we (and probably many more) will have be able to handle multiframe DICOMs. We really like dcmstack and did hope that we could stick to it (or the Nibable replacement), but if the above mentioned timeframe is accurate, then we will need to switch to something like dcmtk.

**Comment by yarikoptic** [comment]
became also a problem for heudiconv:  https://github.com/nipy/heudiconv/issues/582 with the link to sample dicoms at https://github.com/nipy/heudiconv/issues/582#issuecomment-1232589596 .

**Comment by yarikoptic** [comment]
We got another user reporting the same issue in heudiconv: https://github.com/nipy/heudiconv/issues/613 . I wonder on either @matthew-brett et al in czi-nibabel achieved the desired functionality which could be used in dcmstack to handle such DICOMs?

**Comment by moloney** [comment]
I just opened a PR with something that seems to be working for 3D enhanced DICOM files.  Feel free to test it out and give feedback, I just want to add tests before merging.  Adding support for 4D enhanced DICOM files would probably also be doable, but so far isn't a priority for me.

**Comment by psadil** [comment]
What else is needed to get that pull request finished?

**Comment by moloney** [comment]
The branch for PR #84 is in a good enough state for people to start testing. Still some clean up and improvements I want to make before merging, but the bulk of the work is done.  Supports multi-frame files with up to four dimensions thanks in part to the work I recently pushed to `nibabel.nicom`.

**Comment by moloney** [comment]
I went ahead and merged PR #84 into master.  I'm sure there is still room for improvement both here and in Nibabel's dicomwrappers, but at this point it would be better to open more specific issues for anything that comes up.

**Comment by Spenhouet** [comment]
@moloney can you publish a new release? We need a release version to test.

**Comment by moloney** [comment]
I created issue #97 to track what needs to be done for a release. Unless there is an institutional block then installing directly from github is generally quite easy, and any additional testing on real world data sets prior to release would be very helpful.

**Comment by Spenhouet** [comment]
Indeed, we need an official release version for regulatory reasons. I might be able to check out some data soon.
