### ISSUE TITLE
MetaExtractor fails in case some DICOM fields are empty

### ISSUE THREAD

**Issue by josiglo** [moloney/dcmstack#85]
We noticed that `MetaExtractor` fails in `_get_elem_value()` in case some DICOM fields are empty / are of length zero.

For example, if `PatientWeight` is included in a dataset, but empty, MetaExtractor fails in [this](https://github.com/moloney/dcmstack/blob/master/src/dcmstack/extract.py#L423) line with `TypeError: 'NoneType' object is not iterable` as we try to iterate over `value`, which is `None`.

According to the DICOM standard, optional fields such as `PatientWeight` "may or may not be included and could be zero length". ([source](http://dicomlookup.com/type.asp)). Leaving the field empty thus conforms to the standard.

Note that this error only occurs for DICOM fields of [these](https://github.com/moloney/dcmstack/blob/master/src/dcmstack/extract.py#L325-L335) value representations due to [this](https://github.com/moloney/dcmstack/blob/master/src/dcmstack/extract.py#L419) line.

A `None` check in  `_get_elem_value()` would probably fix the issue.

I am aware that the repo is no longer actively maintained but decided to report the issue anyway due to the planned integration into nibabel.

**Comment by Spenhouet** [comment]
@moloney will you push the fix in a small patch release?
